### ISSUE TITLE
2024 Kubecon EU contribfest tracking

### ISSUE THREAD

**Issue by Rozzii** [metal3-io/community#10]
This issue tracks the activities and plans for the 2024 Kubecon EU activities.

Controller (@Rozzii )
Speaker (@lentzi90)

Tasks:

- [ ] Create introduction material for Contribfest in the metal3-doc repo
- [ ] Create the Contribfest GitHub project
- [ ] Assign existing issues to the new project

Feel free to discuss the Contribfest Issue ideas in the comments.

**Comment by Rozzii** [comment]
Contribfest was very good !
Thanks for participating!
